development:
  adapter: postgresql
  encoding: unicode
  database: diet_meals_development

test:
  adapter: postgresql
  encoding: unicode
  database: diet_meals_test

production:
  adapter: postgresql
  encoding: unicode
  database: diet_meals_production
